window.EXPENSE_APP_CONFIG={SUPABASE_URL:'https://mqsvpkbgsjsstzaeupwz.supabase.co',SUPABASE_ANON_KEY:'sb_publishable_BuCMOgg-5hzw53NBSkHTPA_wL0zp9z_'};
(function(){
const font=document.createElement('link');font.rel='stylesheet';font.href='https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800&display=swap';document.head.appendChild(font);
const manifest=document.createElement('link');manifest.rel='manifest';manifest.href='./manifest.webmanifest?v=24';document.head.appendChild(manifest);
const apple=document.createElement('meta');apple.name='apple-mobile-web-app-capable';apple.content='yes';document.head.appendChild(apple);
const appleTitle=document.createElement('meta');appleTitle.name='apple-mobile-web-app-title';appleTitle.content='FinTrack';document.head.appendChild(appleTitle);
document.title='FinTrack';

const style=document.createElement('style');style.textContent=`*{font-family:'Poppins',system-ui,-apple-system,'Segoe UI',sans-serif!important}.top{background:linear-gradient(135deg,#151914,#2a3028)!important}.brand{font-family:Poppins,sans-serif!important;font-weight:700!important;letter-spacing:-.04em!important}.card{border-radius:18px!important;box-shadow:0 8px 28px rgba(25,28,24,.055)!important}.input,.select,.typebox{border-radius:11px!important}.btn{border-radius:11px!important}.theme-toggle{margin-left:auto;border:1px solid rgba(255,255,255,.25);background:rgba(255,255,255,.1);color:#fff;border-radius:999px;padding:8px 13px;font:600 11px Poppins,sans-serif;cursor:pointer;white-space:nowrap}.ak-top-row{display:flex;align-items:center;gap:12px;width:100%}body.dark{background:#0f120f!important;color:#f3f3ee!important}body.dark .app{background:#0f120f!important;color:#f3f3ee!important}body.dark .top{background:linear-gradient(135deg,#0b0d0b,#181d17)!important}body.dark .nav{background:#151915!important;border-color:#303530!important}body.dark .nav button{color:#b9bdb5!important}body.dark .nav .active{background:#f2f2ec!important;color:#151815!important}body.dark .card{background:#1a1e1a!important;border-color:#303530!important;color:#f3f3ee!important}body.dark .hero{background:linear-gradient(135deg,#25231c,#1b201b)!important}body.dark .input,body.dark .select,body.dark .typebox{background:#121512!important;color:#f3f3ee!important;border-color:#414740!important}body.dark .btn.secondary{background:#1a1e1a!important;color:#f3f3ee!important;border-color:#414740!important}body.dark .progress{background:#303630!important}body.dark .bottom{background:#171b17!important;border-color:#303530!important}.settings-list{display:grid;gap:7px}.settings-item{display:flex;justify-content:space-between;align-items:center;gap:8px;padding:9px 10px;border:1px solid var(--line);border-radius:10px;background:#fff}.settings-item small{color:var(--muted)}.settings-sub{display:flex;flex-wrap:wrap;gap:6px;margin-top:7px}.settings-chip{display:inline-flex;align-items:center;gap:5px;padding:5px 8px;border-radius:999px;background:#ecebe4;font-size:11px}.settings-chip button{border:0;background:transparent;cursor:pointer;font-weight:800;color:#777}.settings-note{font-size:11px;color:var(--muted);line-height:1.5}.ak-mobile-settings{display:none!important}@media(max-width:650px){.theme-toggle{padding:7px 10px;font-size:10px}.settings-item{align-items:flex-start}.ak-mobile-settings{display:flex!important;position:fixed;right:12px;bottom:78px;z-index:20;width:42px;height:42px;border:1px solid #c8c8bf;border-radius:50%;background:#fff;color:#20241d;align-items:center;justify-content:center;box-shadow:0 5px 18px rgba(0,0,0,.16);font-size:18px;cursor:pointer}}body.dark .ak-mobile-settings{background:#1a1e1a;color:#f3f3ee;border-color:#414740}`;document.head.appendChild(style);

window.toggleFinTheme=function(){const dark=!document.body.classList.contains('dark');document.body.classList.toggle('dark',dark);localStorage.setItem('fintrack_theme',dark?'dark':'light');const b=document.getElementById('fin-theme-toggle');if(b)b.textContent=dark?'☀ Light':'☾ Dark'};
const initialDark=localStorage.getItem('fintrack_theme')==='dark';

const proto=Element.prototype,desc=Object.getOwnPropertyDescriptor(proto,'innerHTML');
if(desc&&desc.set){Object.defineProperty(proto,'innerHTML',{get:desc.get,set:function(v){if(this.tagName==='BODY'&&typeof v==='string'){
 v=v.replaceAll("AK's Expense Tracker",'FinTrack').replaceAll('AK FinTrack','FinTrack').replaceAll('Private cloud expense tracker','Personal Finance · Cash Flow · Planning').replaceAll('Personal finance · ','Personal Finance · ');
 v=v.replace('<div class="brand">FinTrack</div>','<div class="ak-top-row"><div class="brand"><span class="fin-brand-lockup"><img class="fin-brand-icon" src="./fintrack-icon-192.svg?v=24" alt="FinTrack"><span class="fin-wordmark">Fin<span class="fin-word-gold">Track</span></span></span></div><button id="fin-theme-toggle" class="theme-toggle" onclick="toggleFinTheme()">'+(initialDark?'☀ Light':'☾ Dark')+'</button></div>');
 }desc.set.call(this,v)},configurable:desc.configurable,enumerable:desc.enumerable});}

let setupPatched=false,baseCats=null,basePay=null;
function setupKey(){return 'fintrack_setup_'+(window.user?.id||'guest')}
function readSetup(){try{return JSON.parse(localStorage.getItem(setupKey())||'{"cats":{},"payments":[]}')}catch(e){return{cats:{},payments:[]}}}
function writeSetup(v){localStorage.setItem(setupKey(),JSON.stringify(v))}
function applySetup(){if(typeof CATS==='undefined'||typeof PAY==='undefined'||!window.user)return;if(!baseCats){baseCats=JSON.parse(JSON.stringify(CATS));basePay=[...PAY]}const s=readSetup();Object.keys(CATS).forEach(k=>{if(!baseCats[k])delete CATS[k]});Object.keys(baseCats).forEach(k=>CATS[k]=[...baseCats[k]]);const custom=s.cats||{};Object.keys(custom).forEach(c=>{if(!CATS[c])CATS[c]=[];custom[c].forEach(sub=>{if(sub&&!CATS[c].includes(sub))CATS[c].push(sub)})});PAY.splice(0,PAY.length,...basePay);(s.payments||[]).forEach(p=>{if(p&&!PAY.includes(p))PAY.push(p)})}
window.addCustomCategory=function(){const n=prompt('New category name');if(!n?.trim())return;const s=readSetup();s.cats=s.cats||{};s.cats[n.trim()]=s.cats[n.trim()]||[];writeSetup(s);applySetup();render()};
window.addCustomSub=function(cat){const n=prompt('New sub-category for '+cat);if(!n?.trim())return;const s=readSetup();s.cats=s.cats||{};s.cats[cat]=s.cats[cat]||[];if(!s.cats[cat].includes(n.trim()))s.cats[cat].push(n.trim());writeSetup(s);applySetup();render()};
window.removeCustomSub=function(cat,sub){const s=readSetup();if(!s.cats?.[cat])return;s.cats[cat]=s.cats[cat].filter(x=>x!==sub);if(!s.cats[cat].length)delete s.cats[cat];writeSetup(s);applySetup();render()};
window.removeCustomCategory=function(cat){const s=readSetup();if(!s.cats?.[cat]||!confirm('Remove custom category '+cat+'?'))return;delete s.cats[cat];writeSetup(s);applySetup();render()};
window.addCustomPayment=function(){const n=prompt('New payment method');if(!n?.trim())return;const s=readSetup();s.payments=s.payments||[];if(!s.payments.includes(n.trim()))s.payments.push(n.trim());writeSetup(s);applySetup();render()};
window.removeCustomPayment=function(p){const s=readSetup();s.payments=(s.payments||[]).filter(x=>x!==p);writeSetup(s);applySetup();render()};
window.resetCustomSetup=function(){if(!confirm('Reset your custom categories and payment methods on this device?'))return;localStorage.removeItem(setupKey());applySetup();render()};
function customizationCard(){const s=readSetup(),cats=s.cats||{},payments=s.payments||[];return '<div class="card"><div class="section">Customize FinTrack</div><p class="settings-note">Manage your own categories, sub-categories and payment methods from this device.</p><div class="row" style="margin-top:12px"><b>Categories & sub-categories</b><button class="btn secondary" onclick="addCustomCategory()">+ Category</button></div><div class="settings-list" style="margin-top:9px">'+(Object.keys(cats).length?Object.keys(cats).map(c=>'<div class="settings-item"><div><b>'+esc(c)+'</b><div class="settings-sub">'+(cats[c].length?cats[c].map(sub=>'<span class="settings-chip">'+esc(sub)+' <button onclick="removeCustomSub(\''+esc(c).replaceAll("'","\\'")+'\',\''+esc(sub).replaceAll("'","\\'")+'\')">×</button></span>').join(''):'<small>No custom sub-categories</small>')+'</div></div><div class="actions"><button class="btn secondary" style="padding:6px 9px" onclick="addCustomSub(\''+esc(c).replaceAll("'","\\'")+'\')">+ Sub</button><button class="btn danger" style="padding:6px 9px" onclick="removeCustomCategory(\''+esc(c).replaceAll("'","\\'")+'\')">×</button></div></div>').join(''):'<div class="empty">No custom categories yet.</div>')+'</div><div class="row" style="margin-top:16px"><b>Payment methods</b><button class="btn secondary" onclick="addCustomPayment()">+ Payment</button></div><div class="settings-sub">'+(payments.length?payments.map(p=>'<span class="settings-chip">'+esc(p)+' <button onclick="removeCustomPayment(\''+esc(p).replaceAll("'","\\'")+'\')">×</button></span>').join(''):'<small>No custom payment methods yet.</small>')+'</div><button class="btn secondary" style="margin-top:14px" onclick="resetCustomSetup()">Reset custom setup</button></div>'}
function patchApp(){document.body.classList.toggle('dark',initialDark);if(typeof CATS!=='undefined'&&typeof settings==='function'&&window.user){applySetup();if(!setupPatched){const originalSettings=settings;settings=function(){return originalSettings()+customizationCard()};setupPatched=true}}if(document.querySelector('.app')&&!document.getElementById('ak-mobile-settings')){const b=document.createElement('button');b.id='ak-mobile-settings';b.className='ak-mobile-settings';b.title='Settings';b.textContent='⚙';b.onclick=()=>{if(typeof go==='function')go('settings')};document.body.appendChild(b)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',patchApp);else patchApp();
new MutationObserver(patchApp).observe(document.documentElement,{childList:true,subtree:true});
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js?v=24',{scope:'./',updateViaCache:'none'}).then(r=>r.update()).catch(()=>{}));
})();