window.EXPENSE_APP_CONFIG={SUPABASE_URL:'https://mqsvpkbgsjsstzaeupwz.supabase.co',SUPABASE_ANON_KEY:'sb_publishable_BuCMOgg-5hzw53NBSkHTPA_wL0zp9z_'};
(function(){
  document.title='FinTrack';
  const font=document.createElement('link');font.rel='stylesheet';font.href='https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800&display=swap';document.head.appendChild(font);
  const manifest=document.createElement('link');manifest.rel='manifest';manifest.href='./manifest.webmanifest?v=26';document.head.appendChild(manifest);
  const apple=document.createElement('meta');apple.name='apple-mobile-web-app-capable';apple.content='yes';document.head.appendChild(apple);
  const appleTitle=document.createElement('meta');appleTitle.name='apple-mobile-web-app-title';appleTitle.content='FinTrack';document.head.appendChild(appleTitle);
  const style=document.createElement('style');style.textContent=`*{font-family:'Poppins',system-ui,-apple-system,'Segoe UI',sans-serif!important}.top{background:linear-gradient(135deg,#151914,#2a3028)!important}.brand{font-family:Poppins,sans-serif!important;font-weight:700!important;letter-spacing:-.04em!important}.card{border-radius:18px!important;box-shadow:0 8px 28px rgba(25,28,24,.055)!important}.input,.select,.typebox{border-radius:11px!important}.btn{border-radius:11px!important}.theme-toggle{margin-left:auto;border:1px solid rgba(255,255,255,.25);background:rgba(255,255,255,.1);color:#fff;border-radius:999px;padding:8px 13px;font:600 11px Poppins,sans-serif;cursor:pointer;white-space:nowrap}.ak-top-row{display:flex;align-items:center;gap:12px;width:100%}.fin-brand-lockup{display:inline-flex;align-items:center;gap:10px}.fin-brand-icon{width:34px;height:34px;border-radius:9px}.fin-wordmark{font-weight:700;font-size:24px;letter-spacing:-.045em}.fin-word-gold{color:#d6a33f}body.dark{background:#0f120f!important;color:#f3f3ee!important}body.dark .app{background:#0f120f!important;color:#f3f3ee!important}body.dark .top{background:linear-gradient(135deg,#0b0d0b,#181d17)!important}body.dark .nav{background:#151915!important}body.dark .nav button{color:#b9bdb5!important}body.dark .nav .active{background:#f2f2ec!important;color:#151815!important}body.dark .card{background:#1a1e1a!important;border-color:#303530!important;color:#f3f3ee!important}body.dark .input,body.dark .select,body.dark .typebox{background:#121512!important;color:#f3f3ee!important;border-color:#414740!important}body.dark .btn.secondary{background:#1a1e1a!important;color:#f3f3ee!important;border-color:#414740!important}body.dark .bottom{background:#171b17!important;border-color:#303530!important}.ak-mobile-settings{display:none!important}@media(max-width:650px){.fin-brand-icon{width:30px;height:30px}.fin-wordmark{font-size:21px}.theme-toggle{padding:7px 10px;font-size:10px}.ak-mobile-settings{display:flex!important;position:fixed;right:12px;bottom:78px;z-index:20;width:42px;height:42px;border:1px solid #c8c8bf;border-radius:50%;background:#fff;color:#20241d;align-items:center;justify-content:center;box-shadow:0 5px 18px rgba(0,0,0,.16);font-size:18px;cursor:pointer}}body.dark .ak-mobile-settings{background:#1a1e1a;color:#f3f3ee;border-color:#414740}`;document.head.appendChild(style);

  function storedDark(){return localStorage.getItem('fintrack_theme')==='dark'}
  function syncThemeButton(){const b=document.getElementById('fin-theme-toggle');if(b)b.textContent=document.body.classList.contains('dark')?'☀ Light':'☾ Dark'}
  function setTheme(dark){document.body.classList.toggle('dark',dark);localStorage.setItem('fintrack_theme',dark?'dark':'light');syncThemeButton()}
  window.toggleFinTheme=function(){setTheme(!document.body.classList.contains('dark'))};
  document.body.classList.toggle('dark',storedDark());

  function applyBrand(){
    document.title='FinTrack';
    document.querySelectorAll('.brand').forEach(el=>{if(!el.querySelector('.fin-brand-lockup'))el.innerHTML='<span class="fin-brand-lockup"><img class="fin-brand-icon" src="./fintrack-icon-192.svg?v=26" alt="FinTrack"><span class="fin-wordmark">Fin<span class="fin-word-gold">Track</span></span></span>'});
    document.querySelectorAll('.sub').forEach(el=>{el.innerHTML=el.innerHTML.replace('AK FinTrack','FinTrack').replace('Personal finance','Personal Finance')});
    const top=document.querySelector('.top');if(top&&!document.getElementById('fin-theme-toggle')){const b=document.createElement('button');b.id='fin-theme-toggle';b.className='theme-toggle';b.onclick=window.toggleFinTheme;const brand=top.querySelector('.brand');if(brand){const row=document.createElement('div');row.className='ak-top-row';top.insertBefore(row,brand);row.appendChild(brand);row.appendChild(b)}syncThemeButton()}
    if(document.querySelector('.app')&&!document.getElementById('ak-mobile-settings')){const b=document.createElement('button');b.id='ak-mobile-settings';b.className='ak-mobile-settings';b.title='Settings';b.textContent='⚙';b.onclick=()=>{if(typeof go==='function')go('settings')};document.body.appendChild(b)}
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',applyBrand);else applyBrand();
  new MutationObserver(()=>requestAnimationFrame(applyBrand)).observe(document.documentElement,{childList:true,subtree:true});
  window.addEventListener('storage',e=>{if(e.key==='fintrack_theme')document.body.classList.toggle('dark',storedDark())});
  if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js?v=26',{scope:'./',updateViaCache:'none'}).then(r=>r.update()).catch(()=>{}));
})();