(function(){
const TYPES=['Salary','Freelance / Professional','Business','Bonus','Interest','Rental Income','Other Income'];
function openIncome(){
 let d=document.getElementById('income-modal');if(d){d.remove();return}
 d=document.createElement('div');d.id='income-modal';d.style='position:fixed;inset:0;background:rgba(0,0,0,.45);z-index:100;display:flex;align-items:flex-end;justify-content:center';
 const total=(typeof rows!=='undefined'?rows.filter(x=>x.category==='Income'&&typeof monthOf==='function'&&monthOf(x.date)===(typeof month!=='undefined'?month:monthOf(new Date()))).reduce((s,x)=>s+Number(x.amount),0):0);
 d.innerHTML='<div class="card" style="width:min(680px,100%);margin:0;border-radius:20px 20px 0 0;max-height:90vh;overflow:auto"><div class="row"><div><b>Income</b><div class="muted">This month: ₹'+Math.round(total).toLocaleString('en-IN')+'</div></div><button class="btn secondary" id="income-close">×</button></div><div class="form" style="margin-top:12px"><div class="field"><label>Date</label><input id="income-date" class="input" type="date" value="'+new Date().toISOString().slice(0,10)+'"></div><div class="field"><label>Amount (₹)</label><input id="income-amount" class="input" type="number" min="0.01" step="0.01"></div><div class="field"><label>Income type</label><select id="income-type" class="select">'+TYPES.map(x=>'<option>'+x+'</option>').join('')+'</select></div><div class="field"><label>Description</label><input id="income-desc" class="input" placeholder="e.g. August salary"></div></div><button class="btn gold" style="margin-top:13px;width:100%" id="income-save">Save income</button><div class="section" style="margin-top:18px">Recent income</div><div id="income-list" class="muted" style="margin-top:8px"></div></div>';
 document.body.appendChild(d);document.getElementById('income-close').onclick=()=>d.remove();document.getElementById('income-save').onclick=saveIncome;renderIncomeList();
}
function renderIncomeList(){const el=document.getElementById('income-list');if(!el||typeof rows==='undefined')return;const m=typeof month!=='undefined'?month:monthOf(new Date());const a=rows.filter(x=>x.category==='Income'&&monthOf(x.date)===m).sort((x,y)=>String(y.date).localeCompare(String(x.date)));el.innerHTML=a.length?a.map(x=>'<div class="row" style="padding:7px 0;border-bottom:1px solid var(--line)"><span>'+esc(x.date)+' · '+esc(x.subcategory)+'</span><b>₹'+Math.round(Number(x.amount)).toLocaleString('en-IN')+'</b></div>').join(''):'No income logged this month.'}
async function saveIncome(){const amount=Number(document.getElementById('income-amount').value);if(!amount||amount<=0){alert('Enter a valid income amount.');return}const r=await sb.from('expenses').insert({user_id:user.id,date:document.getElementById('income-date').value,amount,category:'Income',subcategory:document.getElementById('income-type').value,description:document.getElementById('income-desc').value,payment_mode:null});if(r.error){alert(r.error.message);return}await load();openIncome()}
function addIncomeNav(){if(!document.querySelector('.bottom')&&!document.querySelector('.nav'))return;document.querySelectorAll('.ak-income-nav').forEach(x=>x.remove());const bottom=document.querySelector('.bottom');if(bottom){const b=document.createElement('button');b.className='ak-income-nav';b.innerHTML='<span>₹</span><span>Income</span>';b.onclick=openIncome;bottom.insertBefore(b,bottom.lastElementChild)}const nav=document.querySelector('.nav');if(nav){const b=document.createElement('button');b.className='ak-income-nav';b.textContent='Income';b.onclick=openIncome;nav.appendChild(b)}}
const oldRender=window.render;let lastRoot='';function watch(){addIncomeNav();if(document.body.innerHTML.length!==lastRoot){lastRoot=document.body.innerHTML;setTimeout(addIncomeNav,0)}}
window.openIncome=openIncome;setInterval(watch,700);setTimeout(addIncomeNav,300);
})();