(function(){
  const key=()=> 'ak_setup_'+(window.user?.id||'guest');
  const read=()=>{try{return JSON.parse(localStorage.getItem(key())||'{"cats":{},"payments":[]}')}catch(e){return{cats:{},payments:[]}}};
  const save=v=>localStorage.setItem(key(),JSON.stringify(v));
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function open(){
    let old=document.getElementById('ak-settings-modal'); if(old)old.remove();
    const s=read(), cats=s.cats||{}, pays=s.payments||{};
    const m=document.createElement('div'); m.id='ak-settings-modal';
    m.innerHTML='<div class="ak-sm-back"><div class="ak-sm-card"><div class="ak-sm-head"><b>⚙ AK FinTrack Settings</b><button id="ak-sm-close">×</button></div><div class="ak-sm-body"><h3>Categories & Sub-categories</h3><p class="ak-sm-note">Add, rename or remove your personal categories. Built-in categories are not altered.</p><div id="ak-cat-list"></div><button id="ak-add-cat" class="ak-sm-primary">＋ Add Category</button><h3 style="margin-top:22px">Payment Methods</h3><div id="ak-pay-list"></div><button id="ak-add-pay" class="ak-sm-primary">＋ Add Payment Method</button><button id="ak-reset" class="ak-sm-secondary">Reset my custom setup</button></div></div></div>';
    document.body.appendChild(m);
    const list=m.querySelector('#ak-cat-list');
    function render(){
      const x=read(), cc=x.cats||{};
      list.innerHTML=Object.keys(cc).length?Object.keys(cc).map(c=>'<div class="ak-cat"><div class="ak-cat-row"><b>'+esc(c)+'</b><span><button data-edit-cat="'+esc(c)+'">Edit</button><button data-del-cat="'+esc(c)+'" class="danger">Delete</button></span></div><div class="ak-sub-list">'+(cc[c].length?cc[c].map(sub=>'<span class="ak-chip">'+esc(sub)+' <button data-edit-sub="'+esc(c)+'" data-sub="'+esc(sub)+'">✎</button><button data-del-sub="'+esc(c)+'" data-sub="'+esc(sub)+'">×</button></span>').join(''):'<small>No sub-categories</small>')+'</div><button data-add-sub="'+esc(c)+'" class="ak-link">＋ Add sub-category</button></div>').join(''):'<div class="ak-empty">No custom categories yet.</div>';
      m.querySelectorAll('[data-edit-cat]').forEach(b=>b.onclick=()=>{const old=b.dataset.editCat,n=prompt('Rename category',old);if(!n||!n.trim()||n.trim()===old)return;const z=read();z.cats[n.trim()]=z.cats[old]||[];delete z.cats[old];save(z);render();refreshApp()});
      m.querySelectorAll('[data-del-cat]').forEach(b=>b.onclick=()=>{if(!confirm('Delete this custom category and its sub-categories?'))return;const z=read();delete z.cats[b.dataset.delCat];save(z);render();refreshApp()});
      m.querySelectorAll('[data-add-sub]').forEach(b=>b.onclick=()=>{const c=b.dataset.addSub,n=prompt('New sub-category for '+c);if(!n||!n.trim())return;const z=read();z.cats[c]=z.cats[c]||[];if(!z.cats[c].includes(n.trim()))z.cats[c].push(n.trim());save(z);render();refreshApp()});
      m.querySelectorAll('[data-edit-sub]').forEach(b=>b.onclick=()=>{const c=b.dataset.editSub,old=b.dataset.sub,n=prompt('Rename sub-category',old);if(!n||!n.trim()||n.trim()===old)return;const z=read(),a=z.cats[c]||[];z.cats[c]=a.map(v=>v===old?n.trim():v);save(z);render();refreshApp()});
      m.querySelectorAll('[data-del-sub]').forEach(b=>b.onclick=()=>{const c=b.dataset.delSub,sub=b.dataset.sub,z=read();z.cats[c]=(z.cats[c]||[]).filter(v=>v!==sub);if(!z.cats[c].length)delete z.cats[c];save(z);render();refreshApp()});
      const pl=m.querySelector('#ak-pay-list'), ps=(read().payments||[]);pl.innerHTML=ps.length?ps.map(p=>'<span class="ak-chip">'+esc(p)+' <button data-edit-pay="'+esc(p)+'">✎</button><button data-del-pay="'+esc(p)+'">×</button></span>').join(''):'<div class="ak-empty">No custom payment methods yet.</div>';
      pl.querySelectorAll('[data-edit-pay]').forEach(b=>b.onclick=()=>{const old=b.dataset.editPay,n=prompt('Rename payment method',old);if(!n||!n.trim()||n.trim()===old)return;const z=read();z.payments=(z.payments||[]).map(v=>v===old?n.trim():v);save(z);render();refreshApp()});
      pl.querySelectorAll('[data-del-pay]').forEach(b=>b.onclick=()=>{const z=read();z.payments=(z.payments||[]).filter(v=>v!==b.dataset.delPay);save(z);render();refreshApp()});
    }
    function refreshApp(){try{if(typeof applySetup==='function')applySetup();if(typeof render==='function')render()}catch(e){}}
    m.querySelector('#ak-add-cat').onclick=()=>{const n=prompt('New category name');if(!n||!n.trim())return;const z=read();z.cats=z.cats||{};if(!z.cats[n.trim()])z.cats[n.trim()]=[];save(z);render();refreshApp()};
    m.querySelector('#ak-add-pay').onclick=()=>{const n=prompt('New payment method');if(!n||!n.trim())return;const z=read();z.payments=z.payments||[];if(!z.payments.includes(n.trim()))z.payments.push(n.trim());save(z);render();refreshApp()};
    m.querySelector('#ak-reset').onclick=()=>{if(confirm('Reset all your custom categories, sub-categories and payment methods on this device?')){localStorage.removeItem(key());render();refreshApp()}};
    m.querySelector('#ak-sm-close').onclick=()=>m.remove(); render();
  }
  function install(){
    if(!document.getElementById('ak-settings-fab')){const b=document.createElement('button');b.id='ak-settings-fab';b.textContent='⚙';b.title='Settings';b.onclick=open;document.body.appendChild(b)}
    if(!document.getElementById('ak-settings-style')){const st=document.createElement('style');st.id='ak-settings-style';st.textContent=`#ak-settings-fab{position:fixed;right:14px;bottom:78px;width:48px;height:48px;border-radius:50%;border:0;background:#20241d;color:#fff;font-size:22px;z-index:99998;box-shadow:0 5px 18px rgba(0,0,0,.2)}#ak-settings-modal{position:fixed;inset:0;z-index:100000;background:rgba(0,0,0,.45);display:flex;align-items:flex-end;justify-content:center} .ak-sm-back{width:100%;max-width:650px;max-height:92vh;overflow:auto}.ak-sm-card{background:#fff;color:#20241d;border-radius:22px 22px 0 0;padding:0 16px 24px;box-shadow:0 -8px 30px rgba(0,0,0,.18)}.ak-sm-head{position:sticky;top:0;background:#fff;padding:17px 0;border-bottom:1px solid #e4e4df;display:flex;justify-content:space-between;align-items:center;font-size:16px}.ak-sm-head button{border:0;background:transparent;font-size:28px}.ak-sm-body{padding-top:8px}.ak-sm-body h3{font-size:15px;margin:14px 0 5px}.ak-sm-note{font-size:11px;color:#777;line-height:1.5}.ak-cat{border:1px solid #e2e2dc;border-radius:13px;padding:11px;margin:8px 0}.ak-cat-row{display:flex;justify-content:space-between;gap:8px}.ak-cat-row button,.ak-chip button{border:0;background:transparent;font-size:11px;margin-left:5px}.ak-cat-row .danger{color:#b33}.ak-sub-list{display:flex;flex-wrap:wrap;gap:6px;margin:9px 0}.ak-chip{display:inline-flex;align-items:center;background:#eeeee8;border-radius:999px;padding:6px 8px;font-size:11px}.ak-link{border:0;background:transparent;padding:3px 0;font-size:11px}.ak-sm-primary,.ak-sm-secondary{width:100%;padding:11px;border-radius:11px;margin-top:9px;font-weight:600}.ak-sm-primary{border:0;background:#20241d;color:#fff}.ak-sm-secondary{border:1px solid #ccc;background:#fff}.ak-empty{font-size:11px;color:#888;padding:8px 0}@media(min-width:651px){#ak-settings-fab{display:none}}body.dark #ak-settings-modal .ak-sm-card,body.dark #ak-settings-modal .ak-sm-head{background:#1a1e1a;color:#f3f3ee}body.dark #ak-settings-modal .ak-cat{border-color:#414740}body.dark #ak-settings-modal .ak-chip{background:#303630}body.dark #ak-settings-modal .ak-sm-secondary{background:#1a1e1a;color:#f3f3ee;border-color:#414740}`;document.head.appendChild(st)}
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();
