/* v78: optional Expense Groups for trips, events and projects. */
(function(){
  let installed=false;
  const META_GROUPS='__fintrack_groups', META_MAP='__fintrack_expense_groups';
  const readMeta=()=>{const m=typeof typeMap==='function'?typeMap():{};return{groups:Array.isArray(m[META_GROUPS])?m[META_GROUPS]:[],map:(m[META_MAP]&&typeof m[META_MAP]==='object')?m[META_MAP]:{}}};
  const writeMeta=(groups,map)=>{const m=typeMap();m[META_GROUPS]=groups;m[META_MAP]=map;saveTypeMap(m)};
  const groupOf=x=>readMeta().map[String(x?.id)]||'';
  const options=(selected='')=>'<option value="">None</option>'+readMeta().groups.map(g=>`<option value="${esc(g)}" ${g===selected?'selected':''}>${esc(g)}</option>`).join('');
  function addGroup(){const el=$('newExpenseGroup'),name=(el?.value||'').trim();if(!name)return;const d=readMeta();if(!d.groups.some(x=>x.toLowerCase()===name.toLowerCase())){d.groups.push(name);d.groups.sort((a,b)=>a.localeCompare(b));writeMeta(d.groups,d.map)}render()}
  function removeGroup(name){if(!confirm(`Remove expense group “${name}”? Transactions will remain unchanged.`))return;const d=readMeta(),map={};Object.entries(d.map).forEach(([id,g])=>{if(g!==name)map[id]=g});writeMeta(d.groups.filter(g=>g!==name),map);render()}
  function groupSummary(name){if(!name)return'<div class="muted" style="margin-top:10px">Select a group to see its complete spend separately.</div>';const d=readMeta(),all=rows.filter(x=>d.map[String(x.id)]===name),expenses=all.filter(x=>ordinary(x)&&x.category!=='Money Back'),backs=all.filter(x=>x.category==='Money Back'),gross=total(expenses),back=total(backs),net=gross-back,cats={};expenses.forEach(x=>cats[x.category]=(cats[x.category]||0)+Number(x.amount||0));const catItems=Object.entries(cats).sort((a,b)=>b[1]-a[1]);return`<div class="grid kpis" style="margin-top:12px"><div class="card"><div class="label">Total spent</div><div class="value">${money(gross)}</div></div><div class="card"><div class="label">Money Back</div><div class="value" style="color:var(--green)">${money(back)}</div></div><div class="card"><div class="label">Net group cost</div><div class="value">${money(net)}</div></div><div class="card"><div class="label">Transactions</div><div class="value">${expenses.length}</div></div></div>${catItems.length?pieCard('Group spending breakdown',esc(name)+' · Gross spending by category',catItems):'<div class="empty">No expenses recorded in this group yet.</div>'}<div class="tablewrap"><table class="table"><thead><tr><th>Date</th><th>Description</th><th>Category</th><th>Subcategory</th><th>Type</th><th>Amount</th></tr></thead><tbody>${all.slice().sort((a,b)=>String(b.date).localeCompare(String(a.date))).map(x=>`<tr><td>${esc(x.date)}</td><td>${esc(x.description||'—')}</td><td>${esc(x.category)}</td><td>${esc(x.subcategory||'—')}</td><td>${esc(x.category==='Money Back'?'Money Back':typeFor(x))}</td><td>${money(x.amount)}</td></tr>`).join('')}</tbody></table></div>`}
  function groupCard(){const d=readMeta(),selected=window.fintrackGroupView||'';return`<div class="card"><div class="section">Expense Groups</div><div class="muted" style="margin:6px 0 12px">Keep a vacation, event or project together without changing its normal expense categories or types.</div><div class="row" style="align-items:flex-end;flex-wrap:wrap"><div class="field" style="flex:1;min-width:210px"><label>Create group</label><input id="newExpenseGroup" class="input" placeholder="e.g. Goa Vacation · Dec 2026"></div><button class="btn gold" onclick="fintrackAddGroup()">Create</button></div>${d.groups.length?`<div class="field" style="margin-top:14px"><label>View / filter group</label><select class="select" onchange="window.fintrackGroupView=this.value;render()">${'<option value="">Select expense group</option>'+d.groups.map(g=>`<option value="${esc(g)}" ${selected===g?'selected':''}>${esc(g)}</option>`).join('')}</select></div>${selected?`<div class="actions" style="margin-top:8px"><button class="btn secondary" onclick="fintrackRemoveGroup('${String(selected).replace(/\\/g,'\\\\').replace(/'/g,"\\'")}')">Remove group</button></div>`:''}${groupSummary(selected)}`:'<div class="empty">No expense groups created yet.</div>'}</div>`}
  function injectSelectors(){
    if($('expenseType')&&!$('expenseGroup')){const host=$('expenseType').closest('.field')||$('expenseType').parentElement;if(host){const d=document.createElement('div');d.className='field';d.innerHTML='<label>Expense Group <span class="muted">(optional)</span></label><select id="expenseGroup" class="select">'+options(editId?groupOf(rows.find(x=>String(x.id)===String(editId))):'')+'</select>';host.insertAdjacentElement('afterend',d)}}
    if($('backType')&&!$('backExpenseGroup')){const host=$('backType').closest('.field')||$('backType').parentElement;if(host){const d=document.createElement('div');d.className='field';d.innerHTML='<label>Expense Group <span class="muted">(optional)</span></label><select id="backExpenseGroup" class="select">'+options()+'</select>';host.insertAdjacentElement('afterend',d)}}
  }
  async function mapLatest(snap,group,editing){let id=editing;if(!id&&user&&sb){try{let q=sb.from('expenses').select('id,created_at').eq('user_id',user.id).eq('date',snap.date).eq('amount',snap.amount).eq('category',snap.category);if(snap.subcategory)q=q.eq('subcategory',snap.subcategory);const r=await q.order('created_at',{ascending:false}).limit(1);id=r.data?.[0]?.id||null}catch(e){}}if(!id)return;const d=readMeta();if(group)d.map[String(id)]=group;else delete d.map[String(id)];writeMeta(d.groups,d.map)}
  function install(){
    if(installed)return true;if(typeof render!=='function'||typeof settings!=='function'||typeof saveExpense!=='function'||typeof typeMap!=='function'||typeof saveTypeMap!=='function'||typeof pieCard!=='function')return false;
    window.fintrackAddGroup=addGroup;window.fintrackRemoveGroup=removeGroup;
    const oldSettings=settings;settings=function(){return oldSettings.apply(this,arguments)+groupCard()};
    const oldRender=render;render=function(){const r=oldRender.apply(this,arguments);setTimeout(injectSelectors,0);return r};
    const oldSaveExpense=saveExpense;saveExpense=async function(ev){const group=$('expenseGroup')?.value||'',editing=(typeof editId!=='undefined'&&editId)?editId:null,snap={date:$('date')?.value||'',amount:Number($('amount')?.value||0),category:$('category')?.value||'',subcategory:$('subcategory')?.value||''};await oldSaveExpense(ev);await mapLatest(snap,group,editing)};
    if(typeof window.saveMoneyBack==='function'){const oldBack=window.saveMoneyBack;window.saveMoneyBack=async function(ev){const group=$('backExpenseGroup')?.value||'',snap={date:$('backDate')?.value||'',amount:Number($('backAmount')?.value||0),category:'Money Back',subcategory:$('backType')?.value||''};await oldBack(ev);await mapLatest(snap,group,null)}}
    installed=true;setTimeout(injectSelectors,0);return true
  }
  let tries=0;const timer=setInterval(()=>{tries++;if(install()||tries>500)clearInterval(timer)},25);
})();