/* v80: dashboard order — Net Expenses, Monthly Surplus, expense summary, then six KPI tiles. */
(function(){
  let installed=false;
  function install(){
    if(installed)return true;
    if(typeof home!=='function'||typeof monthly!=='function'||typeof incomeMonthly!=='function'||typeof investmentMonthly!=='function'||typeof moneyBackMonthly!=='function'||typeof total!=='function'||typeof pieCard!=='function'||typeof monthLabel!=='function'||typeof savingsHomeCard!=='function')return false;
    const grossByCat=a=>{const m={};(a||[]).filter(x=>ordinary(x)).forEach(x=>m[x.category]=(m[x.category]||0)+Number(x.amount||0));return Object.entries(m).filter(x=>x[1]>0).sort((a,b)=>b[1]-a[1])};
    const grossByType=a=>{const m={'Fixed Recurring':0,'Variable Recurring':0,'Non-Recurring':0,'Uncertain':0};(a||[]).filter(x=>ordinary(x)).forEach(x=>{const t=typeFor(x);if(t in m)m[t]+=Number(x.amount||0)});return m};
    home=function(){
      const a=monthly(month),gross=total(a),back=total(moneyBackMonthly(month)),net=gross-back,income=total(incomeMonthly(month)),invest=total(investmentMonthly(month)),surplus=income+back-gross-invest,t=grossByType(a),catItems=grossByCat(a),typeItems=Object.entries(t).filter(x=>x[1]>0);
      const adjustment=`<div class="card" style="padding:13px 16px"><div class="row" style="gap:18px;flex-wrap:wrap"><div><div class="label">Total spent</div><div class="value" style="font-size:18px">${money(gross)}</div></div><div style="font-size:20px;color:var(--muted)">−</div><div><div class="label">Money back</div><div class="value" style="font-size:18px;color:var(--green)">${money(back)}</div></div><div style="font-size:20px;color:var(--muted)">=</div><div><div class="label">Net expenses</div><div class="value" style="font-size:18px">${money(net)}</div></div></div></div>`;
      return`<div class="monthbar"><button class="btn secondary" onclick="month=moveMonth(month,-1);render()">←</button><b>${monthLabel(month)}</b><button class="btn secondary" onclick="month=moveMonth(month,1);render()">→</button></div><div class="card"><div class="label">Net expenses</div><div class="value">${money(net)}</div><div class="muted">Gross ${money(gross)} − Money Back ${money(back)}</div></div><div class="card"><div class="label">Monthly surplus</div><div class="value" style="color:${surplus>=0?'var(--green)':'var(--red)'}">${money(surplus)}</div><div class="muted">Income + Money Back − Expenses − Investments</div></div>${adjustment}<div class="grid kpis"><div class="card"><div class="label">Fixed recurring</div><div class="value">${money(t['Fixed Recurring'])}</div></div><div class="card"><div class="label">Variable recurring</div><div class="value">${money(t['Variable Recurring'])}</div></div><div class="card"><div class="label">Non-recurring</div><div class="value">${money(t['Non-Recurring'])}</div></div><div class="card"><div class="label">Money Back</div><div class="value" style="color:var(--green)">${money(back)}</div></div><div class="card"><div class="label">Investments</div><div class="value" style="color:var(--gold)">${money(invest)}</div></div><div class="card"><div class="label">Income</div><div class="value" style="color:var(--green)">${money(income)}</div></div></div><div class="pie-pair">${pieCard('Where did my money go?',monthLabel(month)+' · Gross spending by category',catItems)}${pieCard('How is my spending structured?',monthLabel(month)+' · Gross spending by type',typeItems)}</div><div style="height:12px"></div>${savingsHomeCard()}`;
    };
    installed=true;if(typeof render==='function')render();return true;
  }
  let tries=0;const timer=setInterval(()=>{tries++;if(install()||tries>400)clearInterval(timer)},25);
})();